# Generated by Django 6.0.6 on 2026-06-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('inside', 'Inside Dhaka'), ('outside', 'Outside Dhaka')], default='inside', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card'), ('bkash', 'bKash'), ('nagad', 'Nagad')], default='cod', max_length=20),
        ),
    ]
